### PR TITLE
Caverns. Fix node defs/crafting. Smaller emerge. Find cavern floor

### PR DESCRIPTION
**Pull request by paramat**
Large caverns using squashed 3D noise
Less lava, more glowstone, no air pockets
Preserve nether dungeons

Allow light to spread from glowstone and make brighter
Fix 'is ground content' settings, portals should not be
excavated by overgenerated caves
Rack drops itself as normal
Make brick, fence, stair, slab groups consistent
Use 'node sound gravel defaults' for sand
Make brick crafting consistent with default
New fence recipe with output number consistent with default

Make 'emerge area' volume mimimum required size

Add 'find nether target y' function to search for a cavern
floor with space above for nether portal spawn
////////////////////////////

I have made rack drop itself normally, it seems fine to be level 2 so more difficult to mine, but once mined it should not be a 1 in 3 chance of a drop.
The previous 'emerge area' was generating 3x3x3 mapchunks, now it only emerges just enough volume to contain the portal, this will usually cause just a single mapchunk to be generated.
The search for cavern floor cannot detect caves or tunnels created by core mapgen, so portals may still sometimes spawn in dangerous locations, this is fine for some risk factor.

### CODE REVIEW

**Comment by sofar** [comment]
These caves are so huge we need to set a different sky color.

**Comment by paramat** [comment]
Sky usually goes dark when you disable fly, but since we're deep underground a custom skybox would be fine, and could be suitably coloured. Will try to get this PR done very soon.

**Comment by paramat** [comment]
That happened to me too but then i realised i had 'free move' enabled but without fly privilege.
Sky is always dark for me now.

**Comment by paramat** [comment]
Updated, tested and ready for merge.
Nether portals now spawn on cavern floors.

**Comment by sofar** [comment]
That's nice, it's great to spawn at cave bottom.

I do feel that the caves are maybe too large now, it feels like 75% of the volume is air? Maybe go for 50/50 or 25% air?

**Comment by paramat** [comment]
It's 50% air but yeah perhaps a little less is good. I could tune the noise too. Shall i tune now or shall we merge this PR now and i tune later?

**Comment by paramat** [comment]
I'll tune now will only take an hour.

**Comment by sofar** [comment]
I'm probably off to bed at that point. If you don't catch pilzadam online I'll merge it when I get up tomorrow.

**Comment by paramat** [comment]
Ok, i was given push access so perhaps i'll merge it myself later once tuned, if this is ok with you?

**Comment by paramat** [comment]
That's fine,  no rush because i'm going to tackle overgenerated liquids now also.

**Comment by paramat** [comment]
Updated and ready for review/merge.
I managed to remove all overgenerated cave liquids, so no more ugly freestanding towers of lava or water with straight cutoff sides.
This means much less lava but it does spread a lot with time, we could tune it later.
Caverns are smaller and 33% of underground volume. I found a large one that was 250 high by 250 wide by 500 long, impressively big without being overwhelming as they were before.

screenshot_20160529_091034

**Comment by paramat** [comment]
WIP, just need to tune caverns then will push. I'm increasing the cave threshold and noise persistence a little for a more enclosed labyrinthian structure with more emphasis on the smaller detail.

screenshot_20160530_100504

**Comment by sofar** [comment]
I like the various misc changes in this PR to the crafting stuff (honestly, not being sarcastic!)

**Comment by sofar** [comment]
I think this is good and we should go with this. The caves have a nice shape and are not so large that it's all just air. Lava is fairly modest, perhaps you can try and put some small lava lakes in depressions later.

I'm a bit worried about lacking ores, although I suppose netherrack is an ore by itself, and so is glowstone, and both those may be valuable already by themselves as is.

I do find the caves very dark, very very dark. The glowstone doesn't do much to that.

**Comment by paramat** [comment]
Certainly ores could be added, for this mapgen work i just kept it as faithful as possible, others can do ore and feature stuff.

**Pull request merged**
