### PR TITLE
Place portal as schematic. Avoid portal griefing 

### PR DESCRIPTION
**Pull request by paramat**
Should speed stuff up a little.
I also added code for checking the portal creation volume to avoid destroying nodes that are not ground content, to avoid griefing. The search for portal y continues downwards until a good location is found.

### CODE REVIEW

**Comment by sofar** [comment]
Is there a reason we're not using a schematic?

**Comment by paramat** [comment]
Oh crumbs i hadn't thought of that, will do that.

**Comment by paramat** [comment]
Updated. But i think i will add grief checks to this PR. so WIP.

**Comment by paramat** [comment]
Now lighting bugs are sometimes happening using schematics.
if these continue to be bad we could always revert to LVM.

**Comment by paramat** [comment]
Updated with anti-griefing code, but still need to test.
Checking for non 'ground content' nodes is useful as it also avoids the portal spawning in liquids.

**Comment by paramat** [comment]
Bugs, fixing.

**Comment by sofar** [comment]
One thing I didn't check but spotted earlier - the placed portals are always oriented the same way - is there a possibility that we can orient them in the same way as the player-built portal?

**Comment by paramat** [comment]
Ok seems good now, will test one more time.

Matching orientation is possible but will be much more complex. Maybe i'll leave that for others to do. It would be nice to exit the portal in the same direction as entering it.

**Comment by paramat** [comment]
Ok. The anti-griefng seems to work only if the volume checked has been previously generated (either earlier in-game or in a previous game session). This means the portal can spawn in liquid if the destination is ungenerated. This seems not a problem because any player structure needing protection will of course be in a generated area. So i think this is good for merge now.

**Comment by paramat** [comment]
@sofar i know you're busy and tired recently but please can this be merged to avoid portal griefing and make the mod usable?

**Comment by sofar** [comment]
e230813af8695101f64b22cd160cbfbecd2f3699

**Pull request closed without merging**
