### PR TITLE
StairsPlus support for nether bricks.

### PR DESCRIPTION
**Pull request by Lukc**

### CODE REVIEW

**Comment by PilzAdam** [comment]
Why not add this code to the stairs plus mod?

**Comment by Lukc** [comment]
I’m not sure. Most of the mods do it that way, because stairsplus offers an API to do just that. Besides, we’re already using the stairs API, and I don’t see how this is any different.

If we decide to change some of the properties of the nether bricks, though, it would be easier to be able to modify the properties of its stairs and slabs as well, which we couldn’t directly do if that code were in moreblocks.

**Comment by sofar** [comment]
This is kinda weird though, we're depending on `moreblocks` to provide the `stairsplus` api? That can't be right.

**Comment by Lukc** [comment]
Well… [I think we do](https://github.com/minetest-mods/moreblocks/tree/master/stairsplus)?

I thought it had been quite some time since `stairsplus` was merged into `moreblocks`. Did I miss something? I’m getting kinda confused here.

**Comment by sofar** [comment]
Ahhh, I forgot about that. Such bad APi policy - should really just be a separate mod :/

**Pull request merged**
